kind: Template
apiVersion: v1
parameters:
- name: PSK
  description: "The random private shared key for the VPN server"
  generate: expression
  from: "[a-zA-Z0-9]{12}"
- name: USERNAME
  description: "The random username for the VPN"
  generate: expression
  from: "[a-zA-Z0-9]{12}"
- name: PASSWORD
  description: "The random user password for the VPN"
  generate: expression
  from: "[a-zA-Z0-9]{12}"
objects:
- kind: Secret
  apiVersion: v1
  kind: Secret
  metadata:
    name: vpn
    namespace: tools
  type: Opaque
  data:
    psk: '${PSK}'
    username: '${USERNAME}'
    password: '${PASSWORD}'
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: '2018-10-22T07:48:45Z'
    creationTimestamp: '2018-10-22T07:48:44Z'
    generation: 2
    labels:
      app: ipsec-vpn-server
    name: ipsec-vpn-server
    namespace: tools
    resourceVersion: '2157'
    selfLink: /apis/image.openshift.io/v1/namespaces/tools/imagestreams/ipsec-vpn-server3
    uid: e6a4e1b7-d5ce-11e8-92c1-525400c9c704
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.io/imported-from: hwdsl2/ipsec-vpn-server
      from:
        kind: DockerImage
        name: hwdsl2/ipsec-vpn-server
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: ipsec-vpn-server
    name: ipsec-vpn-server
  spec:
    replicas: 1
    selector:
      app: ipsec-vpn-server
      deploymentconfig: ipsec-vpn-server
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: ipsec-vpn-server
          deploymentconfig: ipsec-vpn-server
      spec:
        serviceAccountName: "userroot"
        containers:
        - env:
          - name: VPN_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: vpn
          - name: VPN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: vpn
          - name: VPN_IPSEC_PSK
            valueFrom:
              secretKeyRef:
                key: psk
                name: vpn
          image: hwdsl2/ipsec-vpn-server@sha256:37b9be10f185b73c12718e72d8b4996886224fe16165a96767feef6926013326
          imagePullPolicy: Always
          name: ipsec-vpn-server
          ports:
          - containerPort: 500
            protocol: UDP
          - containerPort: 4500
            protocol: UDP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /lib/modules
            name: ipsec-vpn-server-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: ipsec-vpn-server-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ipsec-vpn-server
        from:
          kind: ImageStreamTag
          name: ipsec-vpn-server:latest
          namespace: tools
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
