kind: Template
apiVersion: v1
objects:
- kind: Secret
  apiVersion: v1
  kind: Secret
  metadata:
    name: vpn_credentials
    namespace: tools
  type: Opaque
  data:
    psk: '${PSK}'
    username: '${USERNAME}'
    password: '${PASSWORD}'
parameters:
- name: PSK
  description: "The random private shared key for the VPN server"
  generate: expression
  from: "[a-zA-Z0-9]{12}"
- name: USERNAME
  description: "The random username for the VPN"
  generate: expression
  from: "[a-zA-Z0-9]{12}"
- name: PASSWORD
  description: "The random user password for the VPN"
  generate: expression
  from: "[a-zA-Z0-9]{12}"